# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fb41a702c3e4d75b978740cd0913e96a"
name = "greenline-merchant-dev"
handle = "greenline-merchant-dev"
application_url = "https://handbags-pee-accessed-promised.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-9393e1e2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,read_assigned_fulfillment_orders,read_customers,read_discounts,read_draft_orders,read_fulfillments,read_merchant_managed_fulfillment_orders,read_orders,read_payment_terms,read_products,read_returns,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_draft_orders,write_fulfillments,write_merchant_managed_fulfillment_orders,write_orders,write_products,write_returns"

[auth]
redirect_urls = [
  "https://handbags-pee-accessed-promised.trycloudflare.com/auth/callback",
  "https://handbags-pee-accessed-promised.trycloudflare.com/auth/shopify/callback",
  "https://handbags-pee-accessed-promised.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
